# Generated by Django 5.2.15 on 2026-06-15 06:41

import core.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(encoder=core.encoders.JsonSafeEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
