# Generated by Django 5.2.15 on 2026-06-15 09:03

import core.encoders
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('detection', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('tape', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('scoring', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('outcome', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('trading', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('feature_set_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pipeline_config',
            },
        ),
    ]
