# ---
# module: core.migrations.0003_historicalpipelineconfig
# sprint: sprint-3
# story: US-9 AC-9.2
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-15
# dependencies: core.models, simple_history
# ---
# Generated by Django 5.2.15 on 2026-06-15 09:13

import core.encoders
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pipelineconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPipelineConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('detection', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('tape', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('scoring', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('outcome', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('trading', models.JSONField(default=dict, encoder=core.encoders.JsonSafeEncoder)),
                ('feature_set_id', models.PositiveIntegerField(blank=True, null=True)),
                ('model_id', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pipeline config',
                'verbose_name_plural': 'historical pipeline configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
