# ---
# module: core.migrations.0004_pipelinestate
# sprint: sprint-3
# story: US-9 AC-9.3
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-15
# dependencies: core.models
# ---
# Generated by Django 5.2.15 on 2026-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalpipelineconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firehose_active', models.BooleanField(default=False)),
                ('scoring_enabled', models.BooleanField(default=False)),
                ('trading_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pipeline_state',
            },
        ),
    ]
