# ---
# module: core.migrations.0005_token
# sprint: sprint-4
# story: US-14 AC-14.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-15
# dependencies: core.models
# ---
# Generated by Django 5.2.15 on 2026-06-15 12:31

import core.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pipelinestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('mint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pool_address', models.CharField(max_length=64)),
                ('graduated_at', models.DateTimeField()),
                ('graduated_block_time', models.IntegerField()),
                ('dex_source', models.CharField(max_length=64)),
                ('raw_graduation', models.JSONField(encoder=core.encoders.JsonSafeEncoder)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('RECORDING', 'Recording'), ('SCORED', 'Scored'), ('TRADED', 'Traded'), ('SKIPPED', 'Skipped')], default='DETECTED', max_length=20)),
            ],
            options={
                'db_table': 'tokens',
            },
        ),
    ]
