# ---
# module: core.migrations.0006_swap
# sprint: sprint-5
# story: US-17 AC-17.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-15
# dependencies: core.models
# ---
# Generated by Django 5.2.15 on 2026-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint', models.CharField(db_index=True, max_length=64)),
                ('block_time', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('signature', models.CharField(max_length=128)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('vol_sol', models.FloatField()),
                ('vol_usd', models.FloatField()),
                ('sol_usd', models.FloatField()),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('base_reserve', models.BigIntegerField(blank=True, null=True)),
                ('quote_reserve', models.BigIntegerField(blank=True, null=True)),
                ('rel', models.FloatField()),
            ],
            options={
                'db_table': 'swaps',
            },
        ),
    ]
