# ---
# module: core.migrations.0007_swap_swap_mint_block_slot_sig_idx
# sprint: sprint-5
# story: US-17 AC-17.2
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-15
# dependencies: core.models
# ---
# Generated by Django 5.2.15 on 2026-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_swap'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='swap',
            index=models.Index(fields=['mint', 'block_time', 'slot', 'signature'], name='swap_mint_block_slot_sig_idx'),
        ),
    ]
