# ---
# module: core.migrations.0008_snapshot
# sprint: sprint-6
# story: US-23 AC-23.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-16
# dependencies: core.models, core.encoders
# ---
# Generated by Django 5.2.15 on 2026-06-16 04:36

import core.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_swap_swap_mint_block_slot_sig_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('taken_at', models.DateTimeField()),
                ('elapsed_s', models.IntegerField()),
                ('raw', models.JSONField(encoder=core.encoders.JsonSafeEncoder)),
            ],
            options={
                'db_table': 'snapshots',
            },
        ),
    ]
