# ---
# module: core.migrations.0009_featureset
# sprint: sprint-7
# story: US-29 AC-29.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-16
# dependencies: core.models
# ---
# Generated by Django 5.2.15 on 2026-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('math_version', models.CharField(max_length=64)),
                ('columns', models.JSONField(default=list)),
                ('live_servable', models.JSONField(default=list)),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'feature_sets',
            },
        ),
    ]
