# ---
# module: trading.migrations.0001_initial
# sprint: sprint-13
# story: US-64 AC-64.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-18
# dependencies: django, core.encoders
# ---
# Generated by Django 5.x on 2026-06-18

import core.encoders
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_enabled", models.BooleanField(default=False)),
                ("position_size_sol", models.FloatField(default=0.1)),
                ("max_open_positions", models.IntegerField(default=3)),
                ("slippage_tight_bps", models.IntegerField(default=800)),
                ("slippage_normal_bps", models.IntegerField(default=1500)),
                ("slippage_loss_bps", models.IntegerField(default=2500)),
                (
                    "slippage_panic_bps",
                    models.JSONField(
                        default=list,
                        encoder=core.encoders.JsonSafeEncoder,
                    ),
                ),
                ("take_profit_pct", models.FloatField(default=100.0)),
                ("stop_loss_pct", models.FloatField(default=20.0)),
                ("disaster_cap_pct", models.FloatField(default=40.0)),
                ("rug_pull_drop_pct", models.FloatField(default=50.0)),
                ("next_poll_guard_s", models.IntegerField(default=10)),
                ("auto_sell_timer_s", models.IntegerField(default=300)),
                ("trailing_pct", models.FloatField(default=20.0)),
                ("trailing_arm_multiple", models.FloatField(default=1.05)),
                ("trailing_grace_s", models.IntegerField(default=60)),
                ("ceiling_pct", models.FloatField(default=300.0)),
                ("volume_collapse_threshold_pct", models.FloatField(default=10.0)),
                ("concentration_threshold_pct", models.FloatField(default=40.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trading_config",
                "app_label": "trading",
            },
        ),
    ]
