# ---
# module: trading.migrations.0002_position
# sprint: sprint-13
# story: US-64 AC-64.2
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-18
# dependencies: django, trading.migrations.0001_initial
# ---
# Generated by Django 5.x on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mint", models.CharField(db_index=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("model", "Model prediction pipeline"),
                            ("copytrade", "Copy-trade engine"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("observe", "Observe (paper, no capital)"),
                            ("live", "Live (capital at risk)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAPER", "Paper / sandbox position"),
                            ("OPEN", "Open live position"),
                            ("CLOSED", "Closed position"),
                        ],
                        max_length=8,
                    ),
                ),
                ("entry_ts", models.DateTimeField()),
                ("entry_price", models.FloatField()),
                ("size_sol", models.FloatField()),
                ("exit_ts", models.DateTimeField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                (
                    "exit_trigger",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("realized_pnl_sol", models.FloatField(blank=True, null=True)),
                ("realized_pnl_pct", models.FloatField(blank=True, null=True)),
                ("peak_price", models.FloatField(blank=True, null=True)),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trading_positions",
                "app_label": "trading",
            },
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["source", "status"], name="trading_pos_source_status_idx"
            ),
        ),
    ]
