# ---
# module: trading.migrations.0003_stale_timeout
# sprint: sprint-13
# story: US-66 AC-66.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-18
# dependencies: django, trading.migrations.0002_position
# ---
# Generated by Django 5.x on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingsettings",
            name="stale_timeout_s",
            field=models.IntegerField(default=1800),
        ),
    ]
