# ---
# module: trading.migrations.0004_replay_position
# sprint: sprint-13
# story: US-67 AC-67.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-18
# dependencies: django, trading.migrations.0003_stale_timeout
# ---
# Generated by Django 5.x on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_stale_timeout"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replay_run_id", models.CharField(db_index=True, max_length=64)),
                ("mint", models.CharField(db_index=True, max_length=64)),
                ("score", models.FloatField()),
                ("entry_ts", models.DateTimeField(blank=True, null=True)),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("size_sol", models.FloatField()),
                ("enterable", models.BooleanField(default=False)),
                (
                    "unentered_reason",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "exit_trigger",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("realized_pnl_pct", models.FloatField(blank=True, null=True)),
                ("peak_pct", models.FloatField(blank=True, null=True)),
                ("held_s", models.FloatField(blank=True, null=True)),
                ("flow_usd", models.FloatField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("peak_price_abs", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trading_replay_positions",
            },
        ),
        migrations.AddIndex(
            model_name="replayposition",
            index=models.Index(
                fields=["replay_run_id", "mint"],
                name="trading_rep_replay__mint_idx",
            ),
        ),
    ]
