# ---
# module: trading.migrations.0005_position_score
# sprint: sprint-14
# story: US-72 AC-72.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-19
# dependencies: django, trading.migrations.0004_replay_position
# ---
# Generated by Django 5.x on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0004_replay_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
