# Generated by Django 5.2.15 on 2026-06-21 00:07

import core.encoders
import trading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trading_settings_tp12tr15_t1200'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='position',
            new_name='trading_pos_source_96e8b0_idx',
            old_name='trading_pos_source_status_idx',
        ),
        migrations.RenameIndex(
            model_name='replayposition',
            new_name='trading_rep_replay__bf0fa7_idx',
            old_name='trading_rep_replay__mint_idx',
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='auto_sell_timer_s',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='disaster_cap_pct',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='rug_pull_drop_pct',
            field=models.FloatField(default=15.0),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='slippage_panic_bps',
            field=models.JSONField(default=trading.models._default_panic_bps, encoder=core.encoders.JsonSafeEncoder),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='stop_loss_pct',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='take_profit_pct',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='tradingsettings',
            name='trailing_pct',
            field=models.FloatField(default=10.0),
        ),
    ]
