# ---
# module: copytrade.migrations.0001_initial
# sprint: sprint-12
# story: US-58 AC-58.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-18
# dependencies: django
# ---
# Generated by Django 5.2.15 on 2026-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='observe', max_length=10)),
                ('sol_size_per_trade', models.FloatField(default=0.25)),
                ('take_profit_pct', models.FloatField(default=200.0)),
                ('stop_loss_pct', models.FloatField(default=40.0)),
                ('exit_before_graduation', models.BooleanField(default=True)),
                ('curve_completion_exit_pct', models.FloatField(default=90.0)),
                ('max_hold_seconds', models.IntegerField(default=1800)),
                ('max_concurrent_positions', models.IntegerField(default=20)),
                ('copy_only_pumpfun_curve_buys', models.BooleanField(default=True)),
                ('copy_first_buy_only', models.BooleanField(default=True)),
                ('dedupe_token_across_wallets', models.BooleanField(default=True)),
                ('mirror_wallet_sells', models.BooleanField(default=False)),
                ('active_cohort_id', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'copytrade_config',
            },
        ),
    ]
