# Generated by Django 5.2.15 on 2026-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0004_shared_position_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytradeposition',
            name='high_water_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copytradeposition',
            name='size_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copytradeposition',
            name='strategy_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='copytradesettings',
            name='min_trigger_buy_usd',
            field=models.FloatField(default=250.0),
        ),
        migrations.AddField(
            model_name='copytradesettings',
            name='pump_fun_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='copytradesettings',
            name='usd_size_per_trade',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='copytradewallet',
            name='strategy_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('CURVE', 'Curve Completion'), ('TIMER', 'Max Hold Timer'), ('SETTLE', 'Cohort Settlement'), ('TRAIL', 'Trailing Giveback'), ('MIRROR', 'Mirror Wallet Sell')], max_length=10, null=True),
        ),
    ]
