# Generated by Django 5.2.15 on 2026-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copytrade', '0011_copytradeposition_entry_reprice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copytradeposition',
            name='cap_pct',
            field=models.FloatField(blank=True, help_text='US-75 AC-1: slippage cap fraction applied (e.g. 0.15 for 15%).', null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='copy_latency_s',
            field=models.FloatField(blank=True, help_text='US-75 AC-1: seconds from on-chain block_time to our clock arrival. None when block_time was absent from the Helius event.', null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('CURVE', 'Curve Completion'), ('TIMER', 'Max Hold Timer'), ('SETTLE', 'Cohort Settlement'), ('TRAIL', 'Trailing Giveback'), ('MIRROR', 'Mirror Wallet Sell'), ('ENTRY_REJECTED', 'Entry Rejected (Slippage Cap)'), ('VOID', 'Voided (orphaned open, superseded)'), ('GRADUATION', 'Sold at Graduation (curvestage)')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='fill_price',
            field=models.FloatField(blank=True, help_text='US-75 AC-1: our estimated fill price at detection time (curve/AMM state at wallet_buy_ts + copy_latency).', null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='forward_window_s',
            field=models.IntegerField(blank=True, help_text='US-75 AC-2: for ENTRY_REJECTED rows, actual seconds of tape consumed by the counterfactual settler (bounded).', null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='peak_return_pct',
            field=models.FloatField(blank=True, help_text='US-75 AC-2: for ENTRY_REJECTED rows, best return (fraction, e.g. 0.5 = +50%) from rejection ts forward in the recorder tape.', null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='quote_price',
            field=models.FloatField(blank=True, help_text="US-75 AC-1: watched wallet's confirmed fill price (the 'quote').", null=True),
        ),
        migrations.AlterField(
            model_name='copytradeposition',
            name='rug_outcome',
            field=models.BooleanField(blank=True, help_text='US-75 AC-2: for ENTRY_REJECTED rows, True if token dropped >=50% from peak in the forward window (rug signal).', null=True),
        ),
        migrations.AlterField(
            model_name='copytradesettings',
            name='honest_fills_enabled',
            field=models.BooleanField(default=False, help_text='US-75 AC-1: when True, apply honest-fill slippage cap to OBSERVE copy entries and emit ENTRY_REJECTED rows (PnL NULL). Default False — does not affect the running soak until deliberately flipped.'),
        ),
        migrations.AlterField(
            model_name='copytradewallet',
            name='style',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
