# ---
# module: core.tests.test_pf_v2_parity
# sprint: sprint-16
# story: pf-v1-serving-lane
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-28
# dependencies: pytest, json, pathlib, core.pf_features
# ---
"""Parity test: live compute_pf_features == training build_universe.py output (all 13 features).

WHAT THIS TESTS
===============
For each of the 10 real graduated tokens in the committed fixture
``core/tests/fixtures/pf_v2_parity_fixture.json``:

1. Runs ``compute_pf_features(live_swaps, gts)`` — the live 13-feature builder.
2. Asserts each of the 13 features matches the expected value from the training
   ``build_universe.py:day_features`` run within 1e-6 relative tolerance.

FIXTURE ORIGIN
==============
Generated by ``scripts/make_pf_v2_parity_fixture.py`` on 2026-06-28 from
pumpfundata on day 2026-05-01 (10 real graduated tokens).
Expected feature values computed by the TRAINING code (build_universe.py),
not by the code under test (compute_pf_features).

PARITY CONTRACT
===============
Max relative error across all 10 tokens × 13 features must be < 1e-6.
This proves the live builder is byte-identical to the training path for all 13.

FEATURE NAMES (contract order)
===============================
f_value, f_momentum, f_size, f_holders, f_life, f_top1,
new_buyers_last60, new_buyers_last300, diamond_frac, top5_buyer_share,
repeat_buyer_frac, price_ret, price_maxrun

No network, no DB, no model needed — pure feature math assertion.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from core.pf_features import compute_pf_features

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "pf_v2_parity_fixture.json"
_TOLERANCE = 1e-6  # relative tolerance for float comparison

# All 13 features in contract order (trilly_pf_v2 contract.json feature_vector.order)
_V2_FEATURE_NAMES = [
    "f_value",
    "f_momentum",
    "f_size",
    "f_holders",
    "f_life",
    "f_top1",
    "new_buyers_last60",
    "new_buyers_last300",
    "diamond_frac",
    "top5_buyer_share",
    "repeat_buyer_frac",
    "price_ret",
    "price_maxrun",
]


def _rel_err(actual: float, expected: float) -> float:
    """Relative error |actual - expected| / max(|expected|, 1e-12)."""
    return abs(actual - expected) / max(abs(expected), 1e-12)


@pytest.fixture(scope="module")
def parity_records():
    """Load the committed parity fixture."""
    assert _FIXTURE_PATH.is_file(), f"Fixture not found: {_FIXTURE_PATH}"
    with _FIXTURE_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def test_fixture_has_records(parity_records):
    """Fixture must have at least 5 real tokens."""
    assert len(parity_records) >= 5, f"Expected >=5 fixture records, got {len(parity_records)}"


def test_fixture_has_all_13_features(parity_records):
    """Every fixture record must have all 13 expected_features keys."""
    for rec in parity_records:
        expected_keys = set(rec["expected_features"].keys())
        missing = set(_V2_FEATURE_NAMES) - expected_keys
        assert not missing, (
            f"Fixture record {rec['mint'][:20]} missing features: {missing}"
        )


def test_parity_all_13_features(parity_records):
    """All 13 features from live builder match training output within 1e-6 rel error."""
    max_rel_err = 0.0
    worst_token = None
    worst_feat = None
    errors = []

    for rec in parity_records:
        mint = rec["mint"]
        gts = float(rec["gts"])
        expected = rec["expected_features"]
        live_swaps = rec["live_swaps"]

        result = compute_pf_features(live_swaps, gts)
        assert result is not None, f"compute_pf_features returned None for mint={mint}"

        for fname in _V2_FEATURE_NAMES:
            assert fname in result, f"Missing feature {fname} for mint={mint}"
            live_val = float(result[fname])
            exp_val = float(expected[fname])
            rel = _rel_err(live_val, exp_val)
            if rel > max_rel_err:
                max_rel_err = rel
                worst_token = mint
                worst_feat = fname
            if rel > _TOLERANCE:
                errors.append(
                    f"mint={mint[:16]}... feat={fname} live={live_val:.8f} "
                    f"expected={exp_val:.8f} rel_err={rel:.2e}"
                )

    if errors:
        report = "\n  ".join(errors)
        pytest.fail(
            f"Parity failures (max_rel_err={max_rel_err:.2e}, "
            f"worst={worst_feat}@{worst_token[:16]}...):\n  {report}"
        )

    assert max_rel_err < _TOLERANCE, (
        f"Max relative error {max_rel_err:.2e} >= tolerance {_TOLERANCE:.2e} "
        f"(worst: {worst_feat} @ {worst_token})"
    )


def test_parity_feature_count(parity_records):
    """Builder returns exactly 13 features (no extras)."""
    rec = parity_records[0]
    result = compute_pf_features(rec["live_swaps"], float(rec["gts"]))
    assert result is not None
    assert set(result.keys()) == set(_V2_FEATURE_NAMES), (
        f"Feature key mismatch: got {sorted(result.keys())}, "
        f"expected {sorted(_V2_FEATURE_NAMES)}"
    )


def test_locked_6_features_unchanged(parity_records):
    """The 6 locked features (f_value..f_top1) must match v1 behavior exactly."""
    locked_6 = ["f_value", "f_momentum", "f_size", "f_holders", "f_life", "f_top1"]
    # These are also checked in the main parity test; this test explicitly singles them out.
    for rec in parity_records[:3]:
        result = compute_pf_features(rec["live_swaps"], float(rec["gts"]))
        assert result is not None
        for fname in locked_6:
            assert fname in result, f"Locked feature {fname} missing"
            live_val = float(result[fname])
            exp_val = float(rec["expected_features"][fname])
            rel = _rel_err(live_val, exp_val)
            assert rel < _TOLERANCE, (
                f"Locked feature {fname} parity failure: "
                f"live={live_val} expected={exp_val} rel_err={rel:.2e}"
            )


def test_fewer_than_2_swaps_returns_none():
    """Fewer than 2 pre-grad swaps returns None (guard 1)."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
    ]
    assert compute_pf_features(swaps, 200.0) is None


def test_zero_total_sol_returns_none():
    """Zero total SOL (all zero vol_sol) returns None (DROP_ZERO_LEG guard)."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 0.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        {"block_time": 110, "slot": 2, "side": "buy", "vol_sol": 0.0,
         "token_amount": 500, "owner": "BBB", "price": 0.001},
    ]
    assert compute_pf_features(swaps, 200.0) is None


def test_postgrad_swaps_filtered_out():
    """Swaps with block_time > grad_ts are filtered; if only post-grad remain -> None."""
    swaps = [
        {"block_time": 201, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        {"block_time": 202, "slot": 2, "side": "buy", "vol_sol": 2.0,
         "token_amount": 2000, "owner": "BBB", "price": 0.001},
    ]
    assert compute_pf_features(swaps, 200.0) is None


def test_enrich7_zero_buyers_edge_case():
    """When nbuyers=0 (only sells), all enrich7 features = 0."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "sell", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        {"block_time": 110, "slot": 2, "side": "sell", "vol_sol": 1.0,
         "token_amount": 500, "owner": "BBB", "price": 0.002},
    ]
    # Total sol = 2.0 (from sells), so won't fail total_sol guard
    result = compute_pf_features(swaps, 200.0)
    assert result is not None
    enrich7 = [
        "new_buyers_last60", "new_buyers_last300", "diamond_frac",
        "top5_buyer_share", "repeat_buyer_frac",
    ]
    for fname in enrich7:
        assert result[fname] == 0.0, f"{fname} should be 0 with no buyers, got {result[fname]}"
    # f_value = 0 - 2 = -2 (all sells)
    assert abs(result["f_value"] - (-2.0)) < 1e-9


def test_enrich7_no_px_edge_case():
    """When no swaps have price > 0, price_ret and price_maxrun = 0."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.0},
        {"block_time": 110, "slot": 2, "side": "buy", "vol_sol": 2.0,
         "token_amount": 500, "owner": "BBB", "price": 0.0},
    ]
    result = compute_pf_features(swaps, 200.0)
    assert result is not None
    assert result["price_ret"] == 0.0, f"price_ret should be 0, got {result['price_ret']}"
    assert result["price_maxrun"] == 0.0, f"price_maxrun should be 0, got {result['price_maxrun']}"


def test_diamond_frac_no_sellers():
    """If no seller exists, diamond_frac = 1.0 (all buyers are diamonds)."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        {"block_time": 110, "slot": 2, "side": "buy", "vol_sol": 2.0,
         "token_amount": 500, "owner": "BBB", "price": 0.002},
    ]
    result = compute_pf_features(swaps, 200.0)
    assert result is not None
    assert abs(result["diamond_frac"] - 1.0) < 1e-9, f"diamond_frac={result['diamond_frac']}"


def test_repeat_buyer_frac():
    """Wallet with >= 2 buys counts as repeat buyer."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        {"block_time": 110, "slot": 2, "side": "buy", "vol_sol": 1.0,
         "token_amount": 500, "owner": "AAA", "price": 0.002},  # repeat
        {"block_time": 120, "slot": 3, "side": "buy", "vol_sol": 1.0,
         "token_amount": 300, "owner": "BBB", "price": 0.003},
    ]
    result = compute_pf_features(swaps, 200.0)
    assert result is not None
    # 1 of 2 buyers (AAA) is a repeat buyer -> 0.5
    assert abs(result["repeat_buyer_frac"] - 0.5) < 1e-9, (
        f"repeat_buyer_frac={result['repeat_buyer_frac']}"
    )


def test_new_buyers_last60():
    """Only buyers with first buy >= gts-60 count as new_buyers_last60."""
    gts = 1000.0
    swaps = [
        # first buy of AAA at 100 -> not in last 60 (gts-60=940)
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},
        # first buy of BBB at 950 -> in last 60 and last 300
        {"block_time": 950, "slot": 2, "side": "buy", "vol_sol": 1.0,
         "token_amount": 500, "owner": "BBB", "price": 0.002},
        # first buy of CCC at 800 -> in last 300, not last 60
        {"block_time": 800, "slot": 3, "side": "buy", "vol_sol": 1.0,
         "token_amount": 300, "owner": "CCC", "price": 0.003},
    ]
    result = compute_pf_features(swaps, gts)
    assert result is not None
    assert result["new_buyers_last60"] == 1.0, f"new_buyers_last60={result['new_buyers_last60']}"
    assert result["new_buyers_last300"] == 2.0, f"new_buyers_last300={result['new_buyers_last300']}"


def test_price_ret_price_maxrun():
    """price_ret and price_maxrun are computed from price field."""
    gts = 1000.0
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA", "price": 0.001},  # first_px
        {"block_time": 200, "slot": 2, "side": "buy", "vol_sol": 1.0,
         "token_amount": 500, "owner": "BBB", "price": 0.005},  # max_px
        {"block_time": 300, "slot": 3, "side": "buy", "vol_sol": 1.0,
         "token_amount": 300, "owner": "CCC", "price": 0.003},  # last_px
    ]
    result = compute_pf_features(swaps, gts)
    assert result is not None
    # price_ret = last_px/first_px - 1 = 0.003/0.001 - 1 = 2.0
    assert abs(result["price_ret"] - 2.0) < 1e-9, f"price_ret={result['price_ret']}"
    # price_maxrun = max(px)/first_px - 1 = 0.005/0.001 - 1 = 4.0
    assert abs(result["price_maxrun"] - 4.0) < 1e-9, f"price_maxrun={result['price_maxrun']}"
