# ---
# module: core.tests.test_tape_microstructure_ac282
# sprint: sprint-7
# story: US-28 AC-28.2
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-16
# dependencies: core.tape_microstructure, core/tests/fixtures/golden_fixture_t0t2_15s.json
# ---
"""AC-28.2 — G1 function parity gate.

The frozen 15-token golden fixture (core/tests/fixtures/golden_fixture_t0t2_15s.json)
is run through the vendored compute_features and EVERY feature must match the
fixture's expected value within 1e-9 absolute tolerance.

The fixture was generated by scripts/generate_golden_fixture_ac282.py using
solanabilly3/src/tape_microstructure.compute_features as the source-of-record.
Provenance: solanabilly3/scripts/make_microstructure_golden.py.

Tests
-----
test_g1_golden_fixture_all_tokens_all_features
    Iterates over all ~15 tokens and all tape_* features; asserts
    abs(actual - expected) <= 1e-9 per (mint, feature) pair.
    A single assertion failure reports the exact (mint, feature, expected,
    actual, delta) so regressions are immediately locatable.

test_g1_fixture_has_expected_token_count
    Asserts the fixture contains >= 15 tokens (guards against a truncated
    or empty fixture silently passing the parity loop).

test_g1_fixture_coverage_all_buy_case_present
    Asserts at least one all-buy-window token is in the fixture
    (exercises the ALL_BUY_RATIO_SENTINEL path).

test_g1_fixture_coverage_sell_case_present
    Asserts at least one token with sells is in the fixture
    (exercises the sell-fraction / buy-sell-ratio paths).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from core.tape_microstructure import compute_features

# ---------------------------------------------------------------------------
# Load the frozen fixture once at module level
# ---------------------------------------------------------------------------
_FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "golden_fixture_t0t2_15s.json"

with _FIXTURE_PATH.open() as _f:
    _FIXTURE = json.load(_f)

_TOKENS: list[dict] = _FIXTURE["tokens"]
_WINDOW_S: int = _FIXTURE["window_s"]
_BUCKET_S: int = _FIXTURE["bucket_s"]
_TOLERANCE: float = _FIXTURE["float_tolerance"]


# ---------------------------------------------------------------------------
# G1 parity test — the heart of AC-28.2
# ---------------------------------------------------------------------------

def test_g1_golden_fixture_all_tokens_all_features():
    """Every feature of every fixture token must match within 1e-9."""
    failures: list[str] = []

    for token in _TOKENS:
        mint = token["mint_address"]
        swaps = token["swaps"]
        expected = token["expected_features"]

        actual = compute_features(swaps, _WINDOW_S, _BUCKET_S)

        assert actual is not None, (
            f"compute_features returned None for {mint} — fixture has a non-None entry"
        )

        for key, exp_val in expected.items():
            act_val = actual.get(key)
            if act_val is None:
                failures.append(
                    f"{mint}: key '{key}' missing from actual output"
                )
                continue
            delta = abs(act_val - exp_val)
            if delta > _TOLERANCE:
                failures.append(
                    f"{mint}: '{key}' expected={exp_val!r} actual={act_val!r} delta={delta:.2e}"
                )

        # Also assert no extra keys appeared (contract is additive, but flag drift)
        extra = set(actual.keys()) - set(expected.keys())
        if extra:
            failures.append(f"{mint}: unexpected extra keys in actual output: {extra}")

    assert not failures, (
        f"G1 parity FAILED — {len(failures)} mismatches:\n"
        + "\n".join(failures)
    )


# ---------------------------------------------------------------------------
# Guard tests: fixture completeness / coverage
# ---------------------------------------------------------------------------

def test_g1_fixture_has_expected_token_count():
    """Fixture must have >= 15 tokens — guards against silent truncation."""
    assert len(_TOKENS) >= 15, (
        f"Fixture has only {len(_TOKENS)} tokens; expected >= 15. "
        "Re-run scripts/generate_golden_fixture_ac282.py to regenerate."
    )


def test_g1_fixture_coverage_all_buy_case_present():
    """At least one all-buy-window token (exercises ALL_BUY_RATIO_SENTINEL)."""
    all_buy_tokens = [
        t["mint_address"]
        for t in _TOKENS
        if t["expected_features"].get("tape_all_buy_window") == 1
    ]
    assert all_buy_tokens, (
        "Fixture contains no all-buy-window tokens — sentinel path untested. "
        "Add a token whose swaps are all 'buy' side."
    )


def test_g1_fixture_coverage_sell_case_present():
    """At least one token with sell trades (exercises sell-fraction paths)."""
    sell_tokens = [
        t["mint_address"]
        for t in _TOKENS
        if t["expected_features"].get("tape_n_sell", 0) > 0
    ]
    assert sell_tokens, (
        "Fixture contains no tokens with sell trades — sell-fraction path untested."
    )
