# ---
# module: core.tests.test_golden_scores_fixture_ac441
# sprint: sprint-9
# story: US-44 AC-44.1
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-17
# dependencies: pathlib, hashlib, json, pandas, pytest
# ---
"""AC-44.1 — Golden score vector fixture integrity gate.

Banks v3.2's golden score vectors as the permanent offline oracle and verifies
the banked fixture against its MANIFEST content hash.

Golden fixture location:
    lake/golden/golden_scores_v3_2/golden_scores.parquet

MANIFEST location:
    lake/golden/golden_scores_v3_2/MANIFEST.json

MANIFEST schema (LC_ALL=C sorted keys, SHA-256 of decompressed parquet bytes per US-36):
    content_hash          — SHA-256 hex of the raw parquet file bytes
    dataset_id            — "golden_scores_v3_2"
    feature_input_fixture — the frozen feature input fixture used to produce scores
    model_name            — "trilly_pregrad_v3.2"
    model_version         — "trilly_pregrad_v3_2"
    row_count             — number of scored tokens (5)

Provenance:
    Generated by running the 15 v3.2 LightGBM boosters
    (solanatrills/models/trilly_pregrad_v3_2/boosters/) over the banked
    scorer_feature_fixture_ac431.json (5 synthetic tokens).  For each of the
    3 labels (ctrl/oracle/liq), the 5 seed predictions are averaged; the
    per-label scores are pool-percentile-ranked; blend = mean of 3 ranks.

Raw = immutable:
    This fixture is never modified by the serving path.  New golden vectors
    require an explicit re-banking step (regenerate → new MANIFEST hash).

H1 ImportError trap — module-level import of test_golden_scores_fixture_present
must succeed; deletion/rename fails pytest collection before any test runs.

Tests
-----
  test_golden_scores_fixture_present
      The parquet file exists at the committed path.

  test_golden_scores_fixture_loads
      The parquet file loads without error and has the expected columns.

  test_golden_scores_manifest_present
      The MANIFEST.json exists alongside the parquet.

  test_golden_scores_manifest_content_hash_correct
      SHA-256 of the parquet bytes matches the MANIFEST content_hash field
      (immutability gate — any modification breaks this test).

  test_golden_scores_manifest_schema
      MANIFEST carries all required fields: dataset_id, model_version,
      content_hash, feature_input_fixture, model_name, row_count.

  test_golden_scores_row_count_matches_manifest
      DataFrame row count matches MANIFEST row_count.

  test_golden_scores_columns_present
      Parquet has the expected score/rank/blend columns.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

# ---------------------------------------------------------------------------
# H1 ImportError trap (AC-44.3 wires this into the combined parity suite)
# The named gate functions below are imported by AC-44.3's combined gate file.
# Deleting or renaming them causes ImportError at pytest collection time there.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[2]
_GOLDEN_DIR = _REPO_ROOT / "lake" / "golden" / "golden_scores_v3_2"
_PARQUET_PATH = _GOLDEN_DIR / "golden_scores.parquet"
_MANIFEST_PATH = _GOLDEN_DIR / "MANIFEST.json"

_EXPECTED_COLUMNS = {
    "token_idx",
    "ctrl_score",
    "oracle_score",
    "liq_score",
    "ctrl_rank",
    "oracle_rank",
    "liq_rank",
    "blend_score",
}

_REQUIRED_MANIFEST_FIELDS = {
    "content_hash",
    "dataset_id",
    "feature_input_fixture",
    "model_name",
    "model_version",
    "row_count",
}

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_golden_scores_fixture_present() -> None:
    """The golden_scores.parquet fixture exists at the committed path.

    AC-44.1: the fixture is committed/durable — it must be present on any
    clean checkout.  Missing the file means the golden oracle is absent.
    """
    assert _PARQUET_PATH.is_file(), (
        f"Golden score fixture not found at {_PARQUET_PATH}.\n"
        "AC-44.1 requires the golden_scores.parquet to be committed and durable.\n"
        "Re-bank the fixture: run the v3.2 boosters over scorer_feature_fixture_ac431.json."
    )


def test_golden_scores_fixture_loads() -> None:
    """The golden_scores.parquet loads without error as a DataFrame.

    Guards against a corrupted or truncated file being committed — pandas will
    raise on any structural issue.
    """
    try:
        import pandas as pd
    except ImportError:
        pytest.skip("pandas not installed — skipping parquet load test")

    df = pd.read_parquet(_PARQUET_PATH)
    assert len(df) > 0, "Golden scores parquet loaded but is empty"


def test_golden_scores_manifest_present() -> None:
    """The MANIFEST.json exists alongside the golden_scores.parquet.

    AC-44.1 (§US-36 pattern): every dataset entering the lake carries a
    MANIFEST with dataset_id, model/version, content_hash, and row_count.
    """
    assert _MANIFEST_PATH.is_file(), (
        f"MANIFEST.json not found at {_MANIFEST_PATH}.\n"
        "AC-44.1 requires a MANIFEST alongside the golden_scores.parquet."
    )


def test_golden_scores_manifest_content_hash_correct() -> None:
    """SHA-256 of the parquet bytes matches the MANIFEST content_hash.

    This is the immutability gate (AC-44.1 'raw = immutable'): any edit to the
    parquet file — including re-saving with different metadata — breaks this test.
    The hash is computed over the raw (decompressed) parquet bytes, following the
    US-36 pattern for golden fixtures.
    """
    assert _PARQUET_PATH.is_file(), (
        f"Parquet not found at {_PARQUET_PATH} — cannot check content hash."
    )
    assert _MANIFEST_PATH.is_file(), (
        f"MANIFEST not found at {_MANIFEST_PATH} — cannot verify content hash."
    )

    with open(_MANIFEST_PATH, encoding="utf-8") as fh:
        manifest = json.load(fh)

    expected_hash = manifest.get("content_hash", "")
    assert expected_hash, "MANIFEST is missing 'content_hash' field"

    actual_hash = hashlib.sha256(_PARQUET_PATH.read_bytes()).hexdigest()
    assert actual_hash == expected_hash, (
        f"Golden scores fixture has been modified (immutability violated).\n"
        f"  MANIFEST hash : {expected_hash}\n"
        f"  Actual hash   : {actual_hash}\n"
        f"  File          : {_PARQUET_PATH}\n\n"
        "AC-44.1: the golden fixture is raw=immutable.  Re-bank the fixture and "
        "update the MANIFEST to resolve this failure."
    )


def test_golden_scores_manifest_schema() -> None:
    """MANIFEST carries all required fields per the AC-44.1 / US-36 schema.

    Required: content_hash, dataset_id, feature_input_fixture, model_name,
    model_version, row_count.
    """
    assert _MANIFEST_PATH.is_file(), (
        f"MANIFEST not found at {_MANIFEST_PATH}."
    )

    with open(_MANIFEST_PATH, encoding="utf-8") as fh:
        manifest = json.load(fh)

    missing = _REQUIRED_MANIFEST_FIELDS - set(manifest.keys())
    assert not missing, (
        f"MANIFEST is missing required fields: {sorted(missing)}\n"
        f"Required: {sorted(_REQUIRED_MANIFEST_FIELDS)}"
    )

    assert manifest["dataset_id"] == "golden_scores_v3_2", (
        f"Unexpected dataset_id: {manifest['dataset_id']!r} "
        "(expected 'golden_scores_v3_2')"
    )
    assert manifest["model_version"] == "trilly_pregrad_v3_2", (
        f"Unexpected model_version: {manifest['model_version']!r} "
        "(expected 'trilly_pregrad_v3_2')"
    )


def test_golden_scores_row_count_matches_manifest() -> None:
    """DataFrame row count matches the MANIFEST row_count field.

    Guards against partial writes where the parquet is present but incomplete.
    """
    try:
        import pandas as pd
    except ImportError:
        pytest.skip("pandas not installed — skipping row count test")

    assert _PARQUET_PATH.is_file(), f"Parquet not found: {_PARQUET_PATH}"
    assert _MANIFEST_PATH.is_file(), f"MANIFEST not found: {_MANIFEST_PATH}"

    df = pd.read_parquet(_PARQUET_PATH)
    with open(_MANIFEST_PATH, encoding="utf-8") as fh:
        manifest = json.load(fh)

    expected_rows = manifest.get("row_count")
    assert expected_rows is not None, "MANIFEST missing 'row_count'"
    assert len(df) == expected_rows, (
        f"Row count mismatch: parquet has {len(df)} rows, "
        f"MANIFEST says {expected_rows}."
    )


def test_golden_scores_columns_present() -> None:
    """Parquet has all expected score/rank/blend columns.

    Guards against schema drift — if the scorer changes its output columns, the
    golden fixture must be re-banked and this test updated.
    """
    try:
        import pandas as pd
    except ImportError:
        pytest.skip("pandas not installed — skipping column test")

    assert _PARQUET_PATH.is_file(), f"Parquet not found: {_PARQUET_PATH}"

    df = pd.read_parquet(_PARQUET_PATH)
    missing_cols = _EXPECTED_COLUMNS - set(df.columns)
    assert not missing_cols, (
        f"Golden scores parquet is missing columns: {sorted(missing_cols)}\n"
        f"Expected: {sorted(_EXPECTED_COLUMNS)}\n"
        f"Found: {sorted(df.columns)}"
    )
