# ---
# module: core.tests.test_pf_v1_parity
# sprint: sprint-16
# story: pf-v1-serving-lane
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-28
# dependencies: pytest, json, pathlib, core.pf_v1_features, core.pf_v1_scorer
# ---
"""Parity test: live compute_pf_v1_features == training build_universe.py output.

WHAT THIS TESTS
===============
For each of the 8 real graduated tokens in the committed fixture
``core/tests/fixtures/pf_v1_parity_fixture.json``:

1. Runs ``compute_pf_v1_features(live_swaps, gts)`` — the live feature builder
   using the same swap-dict shape as norm_row_to_swap_dict produces.
2. Asserts each of the 6 features matches the expected value from the training
   ``build_universe.py:day_features`` run within 1e-6 relative tolerance.

The fixture was generated by ``make_pf_v1_parity_fixture.py`` on 2026-06-28
from pumpfundata on day 2026-05-01 (8 real graduated tokens).

PARITY CONTRACT
===============
Max relative error across all 8 tokens × 6 features must be < 1e-6.
This proves the live builder is byte-identical to the training path.

No network, no DB, no model needed — pure feature math assertion.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from core.pf_v1_features import compute_pf_v1_features

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "pf_v1_parity_fixture.json"
_TOLERANCE = 1e-6  # relative tolerance for float comparison


def _rel_err(actual: float, expected: float) -> float:
    """Relative error |actual - expected| / max(|expected|, 1e-12)."""
    return abs(actual - expected) / max(abs(expected), 1e-12)


@pytest.fixture(scope="module")
def parity_records():
    """Load the committed parity fixture."""
    assert _FIXTURE_PATH.is_file(), f"Fixture not found: {_FIXTURE_PATH}"
    with _FIXTURE_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


def test_fixture_has_records(parity_records):
    """Fixture must have at least 5 real tokens."""
    assert len(parity_records) >= 5, f"Expected >=5 fixture records, got {len(parity_records)}"


def test_parity_all_features(parity_records):
    """All 6 features from live builder match training output within 1e-6 relative error."""
    max_rel_err = 0.0
    worst_token = None
    worst_feat = None
    errors = []

    for rec in parity_records:
        mint = rec["mint"]
        gts = float(rec["gts"])
        expected = rec["expected_features"]
        live_swaps = rec["live_swaps"]

        result = compute_pf_v1_features(live_swaps, gts)
        assert result is not None, f"compute_pf_v1_features returned None for mint={mint}"

        feature_names = ["f_value", "f_momentum", "f_size", "f_holders", "f_life", "f_top1"]
        for fname in feature_names:
            assert fname in result, f"Missing feature {fname} for mint={mint}"
            live_val = float(result[fname])
            exp_val = float(expected[fname])
            rel = _rel_err(live_val, exp_val)
            if rel > max_rel_err:
                max_rel_err = rel
                worst_token = mint
                worst_feat = fname
            if rel > _TOLERANCE:
                errors.append(
                    f"mint={mint[:16]}... feat={fname} live={live_val:.8f} "
                    f"expected={exp_val:.8f} rel_err={rel:.2e}"
                )

    if errors:
        report = "\n  ".join(errors)
        pytest.fail(
            f"Parity failures (max_rel_err={max_rel_err:.2e}, "
            f"worst={worst_feat}@{worst_token[:16]}...):\n  {report}"
        )

    # Report the actual max error even on pass (for observability)
    assert max_rel_err < _TOLERANCE, (
        f"Max relative error {max_rel_err:.2e} >= tolerance {_TOLERANCE:.2e} "
        f"(worst: {worst_feat} @ {worst_token})"
    )


def test_parity_feature_count(parity_records):
    """Builder returns exactly 6 features (no extras)."""
    rec = parity_records[0]
    result = compute_pf_v1_features(rec["live_swaps"], float(rec["gts"]))
    assert result is not None
    assert set(result.keys()) == {"f_value", "f_momentum", "f_size", "f_holders", "f_life", "f_top1"}


def test_fewer_than_2_swaps_returns_none():
    """Fewer than 2 pre-grad swaps returns None (guard 1)."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA"},
    ]
    assert compute_pf_v1_features(swaps, 200.0) is None


def test_zero_total_sol_returns_none():
    """Zero total SOL (all zero vol_sol) returns None (DROP_ZERO_LEG guard)."""
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy", "vol_sol": 0.0,
         "token_amount": 1000, "owner": "AAA"},
        {"block_time": 110, "slot": 2, "side": "buy", "vol_sol": 0.0,
         "token_amount": 500, "owner": "BBB"},
    ]
    assert compute_pf_v1_features(swaps, 200.0) is None


def test_postgrad_swaps_filtered_out():
    """Swaps with block_time > grad_ts are filtered; if only post-grad remain -> None."""
    swaps = [
        {"block_time": 201, "slot": 1, "side": "buy", "vol_sol": 1.0,
         "token_amount": 1000, "owner": "AAA"},
        {"block_time": 202, "slot": 2, "side": "buy", "vol_sol": 2.0,
         "token_amount": 2000, "owner": "BBB"},
    ]
    assert compute_pf_v1_features(swaps, 200.0) is None


def test_simple_known_values():
    """Verify feature math with a hand-calculable example."""
    # 3 buys (owners A, B, C) and 1 sell (owner A), all pre-grad at gts=1000
    # Graduation time = 1000
    # first_t = 100, mid = 100 + (1000-100)/2 = 550
    # Buys: A=5 SOL @ t=100, B=2 SOL @ t=600, C=3 SOL @ t=800
    # Sells: A=1 SOL @ t=200
    # total_sol = 5 + 2 + 3 + 1 = 11
    # buy_sol = 10, sell_sol = 1
    # f_value = 10 - 1 = 9.0
    # f_size = log1p(11)
    # f_life = 1000 - 100 = 900
    # ub1 (buys t<=550): A (t=100) -> {A} -> 1
    # ub2 (buys t>550):  B (t=600), C (t=800) -> {B, C} -> 2
    # f_momentum = 2 / (1 + 1) = 1.0
    # wallet_net: A bought 100 tok, sold 50 tok -> net +50 > 0
    #             B bought 200 tok -> net +200 > 0
    #             C bought 300 tok -> net +300 > 0
    # f_holders = 3
    # bw: A=5, B=2, C=3; max=5; bw_tot=10; top1=5/10=0.5
    # f_top1 = 0.5
    gts = 1000.0
    swaps = [
        {"block_time": 100, "slot": 1, "side": "buy",  "vol_sol": 5.0, "token_amount": 100, "owner": "A"},
        {"block_time": 200, "slot": 2, "side": "sell", "vol_sol": 1.0, "token_amount": 50,  "owner": "A"},
        {"block_time": 600, "slot": 3, "side": "buy",  "vol_sol": 2.0, "token_amount": 200, "owner": "B"},
        {"block_time": 800, "slot": 4, "side": "buy",  "vol_sol": 3.0, "token_amount": 300, "owner": "C"},
    ]
    result = compute_pf_v1_features(swaps, gts)
    assert result is not None
    assert abs(result["f_value"] - 9.0) < 1e-9, f"f_value={result['f_value']}"
    assert abs(result["f_momentum"] - 1.0) < 1e-9, f"f_momentum={result['f_momentum']}"
    assert abs(result["f_size"] - math.log1p(11.0)) < 1e-9, f"f_size={result['f_size']}"
    assert result["f_holders"] == 3.0, f"f_holders={result['f_holders']}"
    assert abs(result["f_life"] - 900.0) < 1e-9, f"f_life={result['f_life']}"
    assert abs(result["f_top1"] - 0.5) < 1e-9, f"f_top1={result['f_top1']}"
