# ---
# module: core.tests.test_scorer_parity_ac442
# sprint: sprint-9
# story: US-44 AC-44.2
# status: implemented
# created-by: dev-team
# last-updated: 2026-06-17
# dependencies: core.scorer, core.pregrad_features, lightgbm, numpy, pandas, json, pathlib, types, pytest
# ---
"""AC-44.2 — Scorer parity gate: the US-43 serving path reproduces v3.2's golden
score vectors within the documented tolerance, given the same feature inputs and
the same reference pool/distribution.

This is the 'live==offline by construction' proof for the scorer — the scorer
analogue of the T0/G1/G2 swap/feature parity gates.

Artefacts
---------
  Banked feature inputs:
      core/tests/fixtures/scorer_feature_fixture_ac431.json
      (5 synthetic tokens; the same fixture used to generate the golden vectors)

  Banked golden score vectors (AC-44.1 offline oracle):
      lake/golden/golden_scores_v3_2/golden_scores.parquet

  Banked v3.2 boosters (committed alongside the golden oracle):
      lake/golden/golden_scores_v3_2/boosters/<label>_s<seed>.txt
      (15 files: ctrl/oracle/liq × seeds 0–4)

  Reference pool/distribution:
      Built from the same 5-token pool via ReferenceDistribution.from_pool_results().
      Using the pool as the reference is identical to the score_pool() computation
      (the parity invariant from AC-43.2 — same inputs + same reference = same ranks).

Tolerance specification
-----------------------
  atol = 0.0  (exact / bit-for-bit reproduction)

  Justification:
    LightGBM booster.predict() loaded from a text-format (.txt) model file is
    fully deterministic across invocations on the same hardware and library
    version — no random state, no numerical variation.  NumPy float64 arithmetic
    (seed-average via mean(), count-based percentile-rank, mean-of-ranks) is
    likewise deterministic.  The golden fixture was generated by the SAME
    BlendScorer.score_pool() code path over the same boosters and the same feature
    fixture.  Re-running the same path therefore produces identical float64 bits.

    An atol=0.0 tolerance is deliberately strict: any deviation from the golden
    vectors indicates either a code regression in the serving path or corruption
    of the committed booster files.

    If the Docker CI environment changes (different numpy/lightgbm ABI) and
    introduces sub-ULP variation, the tolerance should be relaxed to atol=1e-12
    WITH AN EXPLICIT REASON documented here.  Do not relax it pre-emptively.

H1 ImportError trap
-------------------
  Module-level imports of the named gate functions below anchor them by exact
  name.  Deleting or renaming any of them raises ImportError at pytest collection
  time, failing CI BEFORE any tests run (mirroring AC-32.3/AC-36.3).

  AC-44.3 imports these gate functions into the combined T0/G1/G2 suite to
  extend the 'scores in sync' standing Definition-of-Done line.

Tests
-----
Wiring guard (H1 ImportError trap):
  test_scorer_parity_gate_importable_ac442

Booster fixture integrity:
  test_v3_2_boosters_committed_ac442
  test_v3_2_booster_feature_names_match_meta_ac442

Serving path parity gate (core test — the offline oracle proof):
  test_scorer_path_reproduces_golden_scores_ac442

Per-component parity (label scores / ranks / blend):
  test_scorer_path_label_scores_match_golden_ac442
  test_scorer_path_label_ranks_match_golden_ac442
  test_scorer_path_blend_score_match_golden_ac442

Determinism gate:
  test_scorer_parity_run_twice_byte_identical_ac442
"""
from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from core.pregrad_features import PRE_FEATURE_NAMES

# ---------------------------------------------------------------------------
# H1 ImportError trap — module-level imports; deletion/rename fails collection
# ---------------------------------------------------------------------------
from core.scorer import BlendScorer, ReferenceDistribution

assert BlendScorer  # H1: deleting BlendScorer fails pytest collection
assert ReferenceDistribution  # H1: deleting ReferenceDistribution fails collection

# ---------------------------------------------------------------------------
# Paths — all committed artefacts
# ---------------------------------------------------------------------------

_REPO_ROOT = Path(__file__).resolve().parents[2]
_GOLDEN_DIR = _REPO_ROOT / "lake" / "golden" / "golden_scores_v3_2"
_GOLDEN_PARQUET = _GOLDEN_DIR / "golden_scores.parquet"
_BOOSTER_DIR = _GOLDEN_DIR / "boosters"
_FIXTURE_PATH = _REPO_ROOT / "core" / "tests" / "fixtures" / "scorer_feature_fixture_ac431.json"

_LABELS = ["ctrl", "oracle", "liq"]
_N_SEEDS = 5

# Tolerance — atol=0.0 (exact / bit-for-bit).
# Justification: see module docstring.  Relaxing to atol=1e-12 requires a
# documented reason (ABI change, etc.) — do not relax pre-emptively.
_ATOL = 0.0
_RTOL = 0.0


# ---------------------------------------------------------------------------
# Session-scoped fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def feature_fixture():
    """Banked feature inputs (5 synthetic tokens, frozen fixture)."""
    with _FIXTURE_PATH.open(encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="session")
def v3_2_boosters():
    """Load the 15 committed v3.2 boosters (ctrl/oracle/liq × seeds 0–4).

    Uses the real model artifacts committed under lake/golden/golden_scores_v3_2/boosters/.
    This is NOT the tiny synthetic fixture used in AC-43.1 tests — these are the
    actual trained LightGBM boosters whose predictions compose the golden oracle.
    """
    import lightgbm as lgb

    boosters: dict[str, list] = {}
    for label in _LABELS:
        label_bsts = []
        for seed in range(_N_SEEDS):
            bst_path = _BOOSTER_DIR / f"{label}_s{seed}.txt"
            assert bst_path.is_file(), (
                f"AC-44.2: committed booster not found: {bst_path}\n"
                "The v3.2 boosters must be committed under lake/golden/golden_scores_v3_2/boosters/."
            )
            bst = lgb.Booster(model_file=str(bst_path))
            label_bsts.append(bst)
        boosters[label] = label_bsts
    return boosters


@pytest.fixture(scope="session")
def v3_2_model_entry():
    """Minimal model_entry stub matching v3.2's blend manifest (no DB required)."""
    return SimpleNamespace(
        labels_seeds_manifest={
            "labels": _LABELS,
            "seeds": list(range(_N_SEEDS)),
            "boosters": {
                lbl: [f"boosters/{lbl}_s{s}.txt" for s in range(_N_SEEDS)]
                for lbl in _LABELS
            },
        },
        feature_list=list(PRE_FEATURE_NAMES),
        artifact_dir=str(_BOOSTER_DIR.parent),
    )


@pytest.fixture(scope="session")
def v3_2_scorer(v3_2_model_entry, v3_2_boosters):
    """BlendScorer instantiated with the real v3.2 boosters (the serving path)."""
    return BlendScorer(v3_2_model_entry, v3_2_boosters)


@pytest.fixture(scope="session")
def serving_path_results(v3_2_scorer, feature_fixture):
    """score_pool() results from the real v3.2 boosters over the banked fixture."""
    return v3_2_scorer.score_pool(feature_fixture)


@pytest.fixture(scope="session")
def golden_df():
    """Banked golden score vectors as a DataFrame (immutable offline oracle)."""
    pd = pytest.importorskip("pandas")
    assert _GOLDEN_PARQUET.is_file(), (
        f"Golden scores parquet not found at {_GOLDEN_PARQUET}.\n"
        "AC-44.1 must be satisfied (fixture present and committed) before AC-44.2 can run."
    )
    return pd.read_parquet(_GOLDEN_PARQUET)


# ---------------------------------------------------------------------------
# H1 ImportError trap test
# ---------------------------------------------------------------------------


def test_scorer_parity_gate_importable_ac442() -> None:
    """BlendScorer and ReferenceDistribution are importable (H1 wiring guard).

    Module-level imports above constitute the primary trap; this test is the
    human-readable layer confirming both symbols resolve to callables.
    """
    from core.scorer import BlendScorer as _BS, ReferenceDistribution as _RD

    assert callable(_BS)
    assert callable(_RD)


# ---------------------------------------------------------------------------
# Booster fixture integrity
# ---------------------------------------------------------------------------


def test_v3_2_boosters_committed_ac442() -> None:
    """All 15 v3.2 booster files are committed and present.

    Integrity pre-check for the parity gate: if any booster is missing, the
    serving path cannot load the model and the test would fail with a confusing
    FileNotFoundError rather than a clear parity failure.
    """
    missing = []
    for label in _LABELS:
        for seed in range(_N_SEEDS):
            path = _BOOSTER_DIR / f"{label}_s{seed}.txt"
            if not path.is_file():
                missing.append(str(path.relative_to(_REPO_ROOT)))
    assert not missing, (
        "AC-44.2: missing committed v3.2 booster files:\n"
        + "\n".join(f"  {p}" for p in missing)
        + "\nAll 15 boosters must be committed under lake/golden/golden_scores_v3_2/boosters/."
    )


def test_v3_2_booster_feature_names_match_meta_ac442() -> None:
    """Booster feature_name() matches PRE_FEATURE_NAMES (the repo's feature contract).

    AC-44.2 requires 'the same feature inputs' — this guards against a committed
    booster trained on a different feature set.  A mismatch means the serving path
    would compute different features than the golden oracle expects.
    """
    import lightgbm as lgb

    bst = lgb.Booster(model_file=str(_BOOSTER_DIR / "ctrl_s0.txt"))
    booster_features = bst.feature_name()
    assert list(booster_features) == list(PRE_FEATURE_NAMES), (
        "v3.2 booster feature_name() does not match PRE_FEATURE_NAMES.\n"
        f"Booster:   {booster_features}\n"
        f"Repo:      {list(PRE_FEATURE_NAMES)}\n"
        "The feature contract (PRD §7.4) requires model.feature_list == booster.feature_name()."
    )


# ---------------------------------------------------------------------------
# Serving path parity gate — the offline oracle proof (AC-44.2 core test)
# ---------------------------------------------------------------------------


def test_scorer_path_reproduces_golden_scores_ac442(
    serving_path_results, golden_df
) -> None:
    """The US-43 serving path reproduces v3.2's golden score vectors.

    This is the 'live==offline by construction' proof for the scorer.

    Inputs:
        Feature fixture: scorer_feature_fixture_ac431.json (5 synthetic tokens)
        Reference pool: built from the pool itself (same as golden generation path)
        Boosters: committed v3.2 boosters (ctrl/oracle/liq × seeds 0–4)

    Tolerance: atol=0.0 (exact / bit-for-bit)
        Justification: LightGBM predict() from a text-format model is deterministic;
        NumPy float64 arithmetic (seed-average, count-rank, mean-of-ranks) is
        deterministic; golden was generated by the same code path + same boosters.
        See module docstring for the full tolerance justification.

    Any deviation from atol=0 indicates a code regression in the serving path or
    corruption of the committed booster files.
    """
    N = len(serving_path_results)
    assert N == len(golden_df), (
        f"Pool size mismatch: serving path returned {N} results, "
        f"golden parquet has {len(golden_df)} rows."
    )

    mismatches = []
    for i, result in enumerate(serving_path_results):
        gold_row = golden_df.iloc[i]
        computed_blend = result["blend_score"]
        golden_blend = float(gold_row["blend_score"])
        if not np.isclose(computed_blend, golden_blend, atol=_ATOL, rtol=_RTOL, equal_nan=False):
            mismatches.append(
                f"token {i}: serving_path={computed_blend:.15f} "
                f"golden={golden_blend:.15f} diff={abs(computed_blend - golden_blend):.2e}"
            )

    assert not mismatches, (
        "AC-44.2 scorer parity gate FAILED — serving path blend_scores do not "
        "match the golden oracle within atol=0.0:\n"
        + "\n".join(mismatches)
        + "\n\nThis is the 'scores in sync' gate: a serving path regression or "
        "booster file corruption has broken live==offline parity by construction."
    )


# ---------------------------------------------------------------------------
# Per-component parity (label scores / ranks / blend)
# ---------------------------------------------------------------------------


def test_scorer_path_label_scores_match_golden_ac442(
    serving_path_results, golden_df
) -> None:
    """Per-label seed-averaged predictions match the golden oracle (atol=0).

    label_scores = mean of the 5 seed booster predictions for each label.
    These are the raw floating-point model outputs before percentile-ranking.

    Tolerance: atol=0.0 — same booster text files, same input matrix, same
    numpy mean(), deterministic float64 arithmetic.
    """
    mismatches = []
    for i, result in enumerate(serving_path_results):
        gold_row = golden_df.iloc[i]
        for label in _LABELS:
            col = f"{label}_score"
            computed = result["label_scores"][label]
            golden = float(gold_row[col])
            if not np.isclose(computed, golden, atol=_ATOL, rtol=_RTOL, equal_nan=False):
                mismatches.append(
                    f"token {i} {label}_score: "
                    f"computed={computed:.15f} golden={golden:.15f} "
                    f"diff={abs(computed - golden):.2e}"
                )
    assert not mismatches, (
        "AC-44.2: label_score parity failed (atol=0.0):\n"
        + "\n".join(mismatches)
    )


def test_scorer_path_label_ranks_match_golden_ac442(
    serving_path_results, golden_df
) -> None:
    """Per-label percentile-ranks match the golden oracle (atol=0).

    label_ranks = count-based percentile rank over the 5-token pool.
    Values are exact multiples of 1/N (N=5): 0.2, 0.4, 0.6, 0.8, 1.0.
    These are not all exactly representable in binary float64, but the
    same rounding occurs in both the golden generation and the serving path,
    so the comparison is exact (atol=0).

    Tolerance: atol=0.0 — same counting operation, same inputs.
    """
    mismatches = []
    for i, result in enumerate(serving_path_results):
        gold_row = golden_df.iloc[i]
        for label in _LABELS:
            col = f"{label}_rank"
            computed = result["label_ranks"][label]
            golden = float(gold_row[col])
            if not np.isclose(computed, golden, atol=_ATOL, rtol=_RTOL, equal_nan=False):
                mismatches.append(
                    f"token {i} {label}_rank: "
                    f"computed={computed:.15f} golden={golden:.15f} "
                    f"diff={abs(computed - golden):.2e}"
                )
    assert not mismatches, (
        "AC-44.2: label_rank parity failed (atol=0.0):\n"
        + "\n".join(mismatches)
    )


def test_scorer_path_blend_score_match_golden_ac442(
    serving_path_results, golden_df
) -> None:
    """Blend scores match the golden oracle token-by-token (atol=0).

    blend_score = mean of the 3 label percentile-ranks.
    Same computation, same inputs → same float64 result.

    Tolerance: atol=0.0 — the strictest possible, justified by determinism.
    """
    mismatches = []
    for i, result in enumerate(serving_path_results):
        computed = result["blend_score"]
        golden = float(golden_df.iloc[i]["blend_score"])
        if not np.isclose(computed, golden, atol=_ATOL, rtol=_RTOL, equal_nan=False):
            mismatches.append(
                f"token {i}: computed={computed:.15f} golden={golden:.15f} "
                f"diff={abs(computed - golden):.2e}"
            )
    assert not mismatches, (
        "AC-44.2: blend_score parity failed (atol=0.0):\n"
        + "\n".join(mismatches)
    )


# ---------------------------------------------------------------------------
# Determinism gate — run-twice byte/tol-identical (AC-44.2 requirement)
# ---------------------------------------------------------------------------


def test_scorer_parity_run_twice_byte_identical_ac442(
    v3_2_scorer, feature_fixture
) -> None:
    """Two calls to score_pool() over the same inputs produce byte-identical results.

    AC-44.2 requires 'run-twice byte/tol-identical'.  This test verifies that the
    serving path (BlendScorer.score_pool with real v3.2 boosters) is deterministic
    across invocations — a prerequisite for the offline oracle proof to hold.

    Both calls use the same scorer instance (same loaded boosters), the same
    feature fixture.  The result dicts must be exactly equal (Python ==), meaning
    every float64 value is bit-for-bit identical.
    """
    results1 = v3_2_scorer.score_pool(feature_fixture)
    results2 = v3_2_scorer.score_pool(feature_fixture)
    assert results1 == results2, (
        "AC-44.2 determinism gate FAILED: score_pool() over the same inputs "
        "produced different results across two invocations.\n"
        "The serving path must be deterministic for the offline oracle proof to hold."
    )
